# Default values for sentence.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

sentence: 
  image: 
    version: "2025-02"
  withasync: true 
  withnames: true 
  withdelays: false
  sentence: 
    replicas: 1
    delay: 0 
  word: 
    replicas: 1
    delay: 0 
  apigateway: 
    replicas: 1
